project:
  type: book
  
execute:
  cache: false
  
  
book:
  title: "통계적 예측모형"
  author: "서울시립대 통계학과 이용희"
  date: last-modified
  downloads: [pdf]
  chapters:
    - index.qmd
    - qmd/lse.qmd
    - qmd/inference.qmd
    - qmd/inference2.qmd
    - qmd/modeleval2.qmd
    - qmd/residual.qmd
    - qmd/modelselection.qmd
    - qmd/anova.qmd
    - qmd/ancova.qmd
    - qmd/compute.qmd
    - qmd/extension.qmd
    - qmd/glm.qmd
    - references.qmd
  
  appendices:
    - qmd/math_mat_basic.qmd
    - qmd/math_vector_space.qmd
    - qmd/math_eigen_value.qmd
    - qmd/math_matrix_decomp.qmd
    - qmd/math_vec_cal.qmd
    - qmd/multivar.qmd
    - qmd/quadratic.qmd
    - qmd/mle.qmd
    - qmd/aic.qmd
    - qmd/practice-01.qmd
    - qmd/practice-02.qmd
    - qmd/practice-03.qmd
    - qmd/practice-04.qmd
    - qmd/practice-05.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    lang: ko
    language: custom.yml
    code-fold: false
    code-overflow: wrap
#    embed-resources: true
    citations-hover: true
    footnotes-hover: true
    crossref:
      fig-prefix: 그림   # (default is "Figure")
      tbl-prefix: 표    # (default is "Table")
      eq-prefix: 식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    include-in-header:
      - text: |
          <script type="text/javascript">
           window.MathJax = {
            tex: {
              macros: {
              RR: '{\\mathbb R}',                    // a simple string replacement
              hatmat:'{\\pmb X ({\\pmb X}^t {\\pmb X} )^{-1} {\\pmb X}^t}',
              bold: ['\\boldsymbol{#1}',1] ,     // this macro has one parameter
              pardiff: ['\\frac{\\partial#2}{\\partial#1}', 2, 'x'], // this macro has an optional parameter that defaults to 'x'
              pardifftwo: ['\\frac{\\partial#1}{\\partial#2}', 2],
              pardiffd: ['\\frac{\\partial#1}{\\partial#2^t \\partial#2}', 2],
              pardiffdd: ['\\frac{\\partial#1}{\\partial#3 \\partial#2}', 3],
              norm: ['\\lVert#1\\rVert',1]
            },
            environments: {
            braced: ["\\left\\{", "\\right\\}"]
            }
           }
          };
          </script>
  pdf:
    documentclass: scrbook
    classoption: oneside
    papersize: A4
# 오류 발생     lang: ko
    fontsize: 11pt
    lof: true
    lot: true
    code-overflow: wrap
    language: custom.yml
    latex-auto-install: true
    latex-tinytex: true
    pdf-engine: xelatex
    crossref:
      fig-title: "그림"
      tbl-title: "표"
      fig-prefix:  "그림" # (default is "Figure")
      tbl-prefix: '' #표    # (default is "Table")
      eq-prefix:  '' #식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    include-in-header: latex/preamble.tex
